name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check_code_style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Maven dependencies
        run: mvn --batch-mode --update-snapshots dependency:go-offline

      - name: Check code style
        run: mvn checkstyle:check

  build:
    runs-on: ubuntu-latest
    needs: check_code_style
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package
        env:
          CI: true

      - name: Upload JAR 
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: target/*.jar
